pages:
  stage: deploy
  script:
    - mkdir -p ~/.local/state/zhf
    - ln -s ~/.local/state/zhf data
    - rm -rf public
    - ./scripts/render-page.sh master public
    - ./scripts/render-page.sh release-26.05 public/release-26.05
  interruptible: true
  artifacts:
    paths:
      - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  resource_group: production
  tags:
    - helsinki-hydra-builder01
