[formatter.rustfmt]
command = "rustfmt"
options = ["--edition", "2021"]
includes = ["*.rs"]

[formatter.black]
command = "black"
includes = ["*.py"]

[formatter.shfmt]
command = "shfmt"
options = ["-w", "-s", "-i", "4"]
includes = ["*.sh"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.html", "*.css", "*.yml", "*.yaml", "*.json"]
