# @generated by https://codeberg.org/goldstein/unflake
let
  indirect_deps = {
  };
  specs = rec {
    unflake_github_denful_import-tree_ref_main = {
      type = "github";
      owner = "denful";
      repo = "import-tree";
      rev = "4ebb10ae17d5f1ad366e7aef5b92cb8eecf24f69";
      lastModified = 1784254960;
      narHash = "sha256-iI88R3wHz8wTKQb5orvpc51L/Xr64AJyxid/0MKa/b8=";
    };
    unflake_github_hercules-ci_flake-parts_ref_main = {
      type = "github";
      owner = "hercules-ci";
      repo = "flake-parts";
      rev = "17c9d6cdfc60c64f4ee8d306f9bc0b4ccb51481e";
      lastModified = 1782949081;
      narHash = "sha256-vp6Y/Grm98ESt6ceOkWiHWyZRDV3J1RID4w+6NWK9yA=";
    };
    unflake_github_nix-community_nixpkgs-lib = {
      type = "github";
      owner = "nix-community";
      repo = "nixpkgs.lib";
      rev = "228ab8523d81526e57a6ca342e1a919fb6d246a8";
      lastModified = 1783821755;
      narHash = "sha256-eMPX9S6MKPyUnaOgeRfrG7OKUiAlc1AlcRinMbSB0WA=";
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "753cc8a3a87467296ddd1fa93f0cc3e81120ee46";
      lastModified = 1784120854;
      narHash = "sha256-KesHgItiZPgGX740axSiQLcIQ8D24MDqNpkKYWIek8k=";
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "a47c123a609287a012dfc44d281de2dd4ed13394";
      lastModified = 1784282293;
      narHash = "sha256-IpX7tmVJi9seHg5M4Wuexy78bQDlbntVk1HcT9kFts4=";
    };
    unflake_github_numtide_devshell_ref_main = {
      type = "github";
      owner = "numtide";
      repo = "devshell";
      rev = "255a2b1725a20d060f566e4755dbf571bbbb5f76";
      lastModified = 1768818222;
      narHash = "sha256-460jc0+CZfyaO8+w8JNtlClB2n4ui1RbHfPTLkpwhU8=";
    };
    unflake_github_numtide_treefmt-nix_ref_main = {
      type = "github";
      owner = "numtide";
      repo = "treefmt-nix";
      rev = "db947814a175b7ca6ded66e21383d938df01c227";
      lastModified = 1780220602;
      narHash = "sha256-eynAfOmbmxJnkp7YewvCEbShNnnYJ9gLLqkzsYtBPeM=";
    };
  };
  deps = indirect_deps // builtins.mapAttrs (_: spec: builtins.fetchTree spec) specs;
  injections = rec {
    unflake_github_denful_import-tree_ref_main = {
    };
    unflake_github_hercules-ci_flake-parts_ref_main = {
      nixpkgs-lib = "unflake_github_nix-community_nixpkgs-lib";
    };
    unflake_github_nix-community_nixpkgs-lib = {
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = {
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = {
    };
    unflake_github_numtide_devshell_ref_main = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_github_numtide_treefmt-nix_ref_main = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
  };
  inject = name: flake_path: subdir:
    let
      inputs = builtins.mapAttrs (_: dep: universe.${dep}) injections.${name} // {
        inherit self;
      };
      sourceInfo = deps.${name};
      outPath = "${sourceInfo.outPath}${subdir}";
      outputs = (import "${sourceInfo.outPath}/${flake_path}").outputs inputs;
      self = outputs // sourceInfo // {
        inherit inputs outputs outPath sourceInfo;
        _type = "flake";
        _flake = true;
      };
    in self;
  universe = rec {
    unflake_github_denful_import-tree_ref_main = inject "unflake_github_denful_import-tree_ref_main" "flake.nix" "";
    unflake_github_hercules-ci_flake-parts_ref_main = inject "unflake_github_hercules-ci_flake-parts_ref_main" "flake.nix" "";
    unflake_github_nix-community_nixpkgs-lib = inject "unflake_github_nix-community_nixpkgs-lib" "flake.nix" "";
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = inject "unflake_github_nixos_nixpkgs_ref_nixos-unstable" "flake.nix" "";
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = inject "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable" "flake.nix" "";
    unflake_github_numtide_devshell_ref_main = inject "unflake_github_numtide_devshell_ref_main" "flake.nix" "";
    unflake_github_numtide_treefmt-nix_ref_main = inject "unflake_github_numtide_treefmt-nix_ref_main" "flake.nix" "";
  };
  inputs = {
    devshell = universe.unflake_github_numtide_devshell_ref_main;
    flake-parts = universe.unflake_github_hercules-ci_flake-parts_ref_main;
    import-tree = universe.unflake_github_denful_import-tree_ref_main;
    nixpkgs = universe.unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    treefmt-nix = universe.unflake_github_numtide_treefmt-nix_ref_main;
  };
in inputs // {
  withInputs = fn: let outputs = fn (inputs // { inherit self; }); self = outputs // {
    inherit inputs outputs;
    _type = "flake";
    outPath = builtins.toString ./.;
  }; in self;
  __functor = self: self.withInputs;
  self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
  _unflake = { inherit specs deps injections; };
}
